name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag backuptools/postgres-backup-s3:${{steps.vars.outputs.sha_short}} --tag backuptools/postgres-backup-s3
    - name: Login to Dockerhub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push the Docker image
      run:  docker push backuptools/postgres-backup-s3:${{steps.vars.outputs.sha_short}}
    - name: Push the :latest Docker image
      run:  docker push backuptools/postgres-backup-s3
